#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'fener-console','console_scripts','driver_keyboard'
__requires__ = 'fener-console'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('fener-console', 'console_scripts', 'driver_keyboard')()
    )
